/** shadcn/ui component library — generated by shadcn/ui CLI.
 *
 * All shadcn/ui primitives are re-exported here for consistent imports.
 * shadcn/ui components use Radix UI primitives + Tailwind CSS styling.
 */

import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Re-export Radix primitives
export { Slot } from "@radix-ui/react-slot";
export type { SlotProps } from "@radix-ui/react-slot";

// Button
export { Button, buttonVariants } from "@/components/ui/button";
export type { ButtonProps } from "@/components/ui/button";

// Input
export { Input } from "@/components/ui/input";

// Card
export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";

// Dialog
export {
  Dialog,
  DialogPortal,
  DialogOverlay,
  DialogClose,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";

// Dropdown
export {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuCheckboxItem,
  DropdownMenuRadioItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuGroup,
  DropdownMenuPortal,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuRadioGroup,
} from "@/components/ui/dropdown-menu";

// Tabs
export { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";

// Tooltip
export {
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
} from "@/components/ui/tooltip";

// Avatar
export { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

// Scroll area
export { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";

// Separator
export { Separator } from "@/components/ui/separator";

// Badge
export { Badge, badgeVariants } from "@/components/ui/badge";
export type { BadgeProps } from "@/components/ui/badge";

// Skeleton
export { Skeleton } from "@/components/ui/skeleton";

// Sonner (toast)
export { Toaster } from "sonner";
export { toast } from "sonner";
